version: "3"
services:
  flask:
    build:
      context: .
    container_name: assict_flask
    restart: always
    command: python api.py
    ports:
      - 5000:5000
    depends_on:
      - rabbit
    volumes:
      - ./temp:/app/temp
  rabbit:
    container_name: assict_rabbit
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  worker:
    container_name: assict_worker_1
    build:
      context: .
    hostname: worker
    command: celery -A tasks worker --pool threads --loglevel INFO
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - ./temp:/app/temp
  flower:
    container_name: assict_flower
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbit
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
