version: "3"
services:
  flask:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A tasks worker --loglevel=info -Q workerA
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit

