version: "3"
services:
  flask:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info --pool=threads
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
  flower:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
